# This workflow will execute all the tests and create a report when merging code to main

name: Regression Testing

on:
  push:
    branches:
      - main # Trigger this workflow only when pushing to the main branch
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install
        pip install flake8 pytest
        poetry run playwright install --with-deps
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        email_password: ${{ secrets.EMAIL_PASSWORD }}
        send_email: true
        CI: true
      run: |
        poetry run pytest -m "sanity or regression" --alluredir=allure-results
        
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

    - name: Upload video artifacts
      uses: actions/upload-artifact@v3
      with:
        name: workflow-videos
        path: videos/
        